export { default as AboutMe } from "./AboutMe/AboutMe"
export { default as Home } from "./Home/Home"
export { default as Projects } from "./Projects/Projects"
export { default as ContactMe } from "./ContactMe/ContactMe"
export { default as NotFound } from "./NotFound/NotFound"